import { NextResponse } from 'next/server';
import pkg from '../../../../package.json';
import buildInfo from '@/generated/build-info.json';

// Separate from /api/health on purpose (see docs/deployment.md#known-gaps).
// A healthcheck that does work can fail for reasons unrelated to service
// health and get a healthy container restarted — /api/health stays a
// trivial `{ status: 'ok' }`. This endpoint exists purely to answer "what
// build is actually running", so it's never wired into any healthcheck.
//
// `buildInfo` is generated by the Dockerfile's builder stage (RUN before
// `npm run build`) and imported as a static JSON module — Next inlines its
// value into the compiled route handler at build time. That means:
//   - Zero runtime configuration: nothing to set in Dokploy for this to work.
//   - The committed src/generated/build-info.json ("unknown"/"unknown") is
//     what `npm run dev` / a non-Docker build sees.
//   - Docker layer caching does the right thing: the RUN step that writes
//     this file sits after `COPY . .`, so it only re-executes (and only
//     the timestamp changes) when the source actually changed. If the code
//     is identical, the layer is reused and the value stays the same — the
//     image IS the same, so it should report the same build.
export function GET() {
  return NextResponse.json({
    version: pkg.version,
    buildTimestamp: buildInfo.timestamp,
    commitSha: buildInfo.commitSha,
  });
}
